# Generated by Django 5.1.3 on 2024-12-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassificationType',
            new_name='ClarificationType',
        ),
        migrations.RemoveField(
            model_name='general',
            name='Due_date',
        ),
        migrations.AlterField(
            model_name='general',
            name='rfx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfx', to='taskapp.rfx'),
        ),
    ]
